[package]
name = "radstudio-macros"
version = "0.1.0"
edition.workspace = true
description = "Macros for radstudio crate"
repository = "https://github.com/Delphier/radstudio"
homepage = "https://github.com/Delphier/radstudio"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.5"
